#!/usr/bin/env node
/**
 * check_manifest.js — Validates the manifest V3 generated by WXT.
 *
 * Runs AFTER `wxt build` (or `wxt prepare`), against:
 *   .output/chrome-mv3/manifest.json
 *   .output/firefox-mv3/manifest.json (if present)
 *
 * Fails hard on:
 *   - manifest_version != 3
 *   - `content_security_policy` contains 'unsafe-eval' or 'unsafe-inline' for scripts
 *   - presence of deprecated MV2 keys (browser_action, page_action, background.persistent)
 *   - host_permissions contains <all_urls> without explicit justification via env DISCIPLINE_ALLOW_ALL_URLS=1
 *
 * Warns (non-zero only when --strict):
 *   - Any permission declared but not referenced in source files
 */
import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'

const OUTPUT_ROOT = '.output'
const TARGETS = ['chrome-mv3', 'firefox-mv3']

const errors = []
const warnings = []

function check(targetDir) {
  const manifestPath = join(OUTPUT_ROOT, targetDir, 'manifest.json')
  if (!existsSync(manifestPath)) {
    warnings.push(`[${targetDir}] manifest.json not found at ${manifestPath} — run \`wxt build\` first`)
    return
  }
  const raw = readFileSync(manifestPath, 'utf8')
  let manifest
  try {
    manifest = JSON.parse(raw)
  } catch (e) {
    errors.push(`[${targetDir}] manifest.json is not valid JSON: ${e.message}`)
    return
  }

  if (manifest.manifest_version !== 3) {
    errors.push(`[${targetDir}] manifest_version is ${manifest.manifest_version}, expected 3`)
  }

  const mv2Keys = ['browser_action', 'page_action']
  for (const key of mv2Keys) {
    if (manifest[key]) {
      errors.push(`[${targetDir}] deprecated MV2 key "${key}" present; use "action" in MV3`)
    }
  }

  if (manifest.background?.persistent === true) {
    errors.push(`[${targetDir}] background.persistent: true is MV2 pattern; MV3 uses ephemeral service worker`)
  }

  const csp = manifest.content_security_policy
  if (csp) {
    const stringified = typeof csp === 'string' ? csp : JSON.stringify(csp)
    if (/unsafe-eval/.test(stringified)) {
      errors.push(`[${targetDir}] CSP contains 'unsafe-eval' — prohibited by MV3 and by NN`)
    }
    if (/unsafe-inline/.test(stringified) && /script-src/i.test(stringified)) {
      errors.push(`[${targetDir}] CSP allows 'unsafe-inline' for scripts — remove`)
    }
  }

  const hostPerms = manifest.host_permissions ?? []
  if (hostPerms.includes('<all_urls>') && !process.env.DISCIPLINE_ALLOW_ALL_URLS) {
    errors.push(
      `[${targetDir}] host_permissions contains <all_urls>. Set DISCIPLINE_ALLOW_ALL_URLS=1 to acknowledge the CWS review impact, or narrow the scope.`,
    )
  }
}

for (const target of TARGETS) {
  check(target)
}

if (warnings.length) {
  console.warn('\n[check-manifest] Warnings:')
  for (const w of warnings) console.warn('  • ' + w)
}

if (errors.length) {
  console.error('\n[check-manifest] FAILED:')
  for (const e of errors) console.error('  • ' + e)
  process.exit(1)
}

if (!warnings.length) {
  console.log('[check-manifest] OK — manifest(s) pass MV3 rules')
}
